# Generated by Django 3.1.3 on 2020-12-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='First_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='Last_name',
        ),
        migrations.AddField(
            model_name='user',
            name='Full_name',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
