# Generated by Django 3.1.3 on 2020-11-26 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=100)),
                ('images', models.ImageField(upload_to='')),
                ('tipo', models.CharField(choices=[('GM', 'Console Game'), ('YGOC', 'Yugioh Card'), ('MGC', 'Magic Card'), ('PKMNC', 'Pokémon Card')], max_length=30)),
                ('country', models.CharField(max_length=120)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('Language', models.CharField(max_length=120)),
                ('Card_condition', models.CharField(choices=[('NM', 'NM'), ('LP', 'LP'), ('MP', 'MP'), ('HP', 'HP'), ('D', 'D')], max_length=30)),
                ('Game_condition', models.CharField(choices=[('Nw', 'New'), ('LN', 'Like-New'), ('US', 'Used')], max_length=30)),
            ],
        ),
    ]
